# Generated by Django 5.2.6 on 2025-10-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_otp_phone_otp_identifier_alter_otp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='identifier',
            field=models.EmailField(max_length=254),
        ),
    ]
