# Generated by Django 5.2.6 on 2025-10-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_otp_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='identifier',
            field=models.CharField(max_length=255),
        ),
    ]
