# Generated by Django 5.2.6 on 2025-09-30 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceDetail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='service',
        ),
        migrations.RemoveField(
            model_name='review',
            name='service',
        ),
    ]
