# Generated by Django 5.2.6 on 2025-10-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackSection1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='callback/')),
                ('title', models.CharField(default='Professional Emergency Electrician - Fast & Reliable', max_length=255)),
                ('subtitle', models.TextField(blank=True, default='24-hour Electrician In Electric dreams. Call Our Professional Electricians Now To Get Help Fast')),
                ('stars_count', models.PositiveSmallIntegerField(default=5)),
                ('reviews_text', models.CharField(blank=True, default='Over 215 google reviews', max_length=255)),
                ('call_image', models.ImageField(blank=True, null=True, upload_to='callback/')),
                ('phone_number', models.CharField(blank=True, default='(+91)1234567890', max_length=80)),
                ('feature_cards', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CallbackSection2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Quality Workmanship', max_length=255)),
                ('paragraphs', models.JSONField(blank=True, default=list)),
                ('phone', models.CharField(blank=True, default='+611234567890', max_length=80)),
                ('image', models.ImageField(blank=True, null=True, upload_to='callback/section2/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CallbackSection3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(default='Get in Touch with Electric Dreams Electrical Today', max_length=255)),
                ('phone', models.CharField(blank=True, default='(+91)1234567890', max_length=80)),
                ('section_title', models.CharField(default='Signs you need an emergency electrician', max_length=255)),
                ('intro', models.TextField(blank=True, default='Many signs indicate when it’s time to call a 24 hour electrician for help with your electrical problems. Here’s a quick list of what to look for:')),
                ('points', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
